### ISSUE TITLE
Spike on geocoder in IS

### ISSUE THREAD

**Issue by tabuchid** [thesquarefoot/nyc-geosupport#8]
Google library and NYC geobindings

Started an exploration doc
https://www.notion.so/squarefoot/nyc-geosupport-in-python-7df26bbc66ea431692a820c30f74cb33

**Comment by sforsell** [comment]
putting this down in favor of improved error handling, next steps are lined out in doc

**Comment by tabuchid** [comment]
I think we can call the doc the results of the spike. Next steps we'll ticket in the next sprint planning.
